### ISSUE TITLE
Possible CMD Option??

### ISSUE THREAD

**Issue by ste2w** [Karleener/FreeDcpPlayer#2]
Hey i was just curious if there was an option where you could run this with out the gui? and just use the player with the command prompt like for example (Freedcpplayer.exe "Pathtodcp") like i said i was just curious i dont know if its possible or not or if it could be implemented in a future version maybe?

**Comment by ste2w** [comment]
adding to that what about command switches like -fs (full screen) -5.1 -np (no initial pause) --exit (exit after play back)

**Comment by Karleener** [comment]
It  was the case in previous alpha version : there was 2 exe files, the Gui lunching the command file based exe. This structure is still in the source code, however the command line is long, for example 
FreeDcpPlayer.exe "B:\dcp_test\dcp2cpl\dcp2cpl\Dcp2cpl_TST-1-25_F-239_51_2K_20220214_SMPTE_OV" -a 1 -d 1 -c 0 -i -v 2>freedcpplayer.log & pause
so and I don't think that many users want to write it. Moreover the Gui lists the available hardware, displays and audio, which can change if you connect/disconnect hardware, so it seems to me more easy to use than command prompt.

**Comment by ste2w** [comment]
oh ok i see i don't mind typing but i see what ypu mean ok thank you for your time! ill close this out :)

**Comment by Karleener** [comment]
Hi, I added the command option in the 0.6.1 release !
